# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from driver.v1 import operation_service_pb2 as driver_dot_v1_dot_operation__service__pb2
from driver.v1 import types_pb2 as driver_dot_v1_dot_types__pb2

GRPC_GENERATED_VERSION = '1.74.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in driver/v1/operation_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class OperationServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetOperation = channel.unary_unary(
                '/nodeplane.driver.v1.OperationService/GetOperation',
                request_serializer=driver_dot_v1_dot_operation__service__pb2.GetOperationRequest.SerializeToString,
                response_deserializer=driver_dot_v1_dot_types__pb2.Operation.FromString,
                _registered_method=True)
        self.WatchOperation = channel.unary_stream(
                '/nodeplane.driver.v1.OperationService/WatchOperation',
                request_serializer=driver_dot_v1_dot_operation__service__pb2.WatchOperationRequest.SerializeToString,
                response_deserializer=driver_dot_v1_dot_types__pb2.OperationEvent.FromString,
                _registered_method=True)
        self.ListOperations = channel.unary_unary(
                '/nodeplane.driver.v1.OperationService/ListOperations',
                request_serializer=driver_dot_v1_dot_operation__service__pb2.ListOperationsRequest.SerializeToString,
                response_deserializer=driver_dot_v1_dot_operation__service__pb2.ListOperationsResponse.FromString,
                _registered_method=True)


class OperationServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetOperation(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def WatchOperation(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListOperations(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_OperationServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetOperation': grpc.unary_unary_rpc_method_handler(
                    servicer.GetOperation,
                    request_deserializer=driver_dot_v1_dot_operation__service__pb2.GetOperationRequest.FromString,
                    response_serializer=driver_dot_v1_dot_types__pb2.Operation.SerializeToString,
            ),
            'WatchOperation': grpc.unary_stream_rpc_method_handler(
                    servicer.WatchOperation,
                    request_deserializer=driver_dot_v1_dot_operation__service__pb2.WatchOperationRequest.FromString,
                    response_serializer=driver_dot_v1_dot_types__pb2.OperationEvent.SerializeToString,
            ),
            'ListOperations': grpc.unary_unary_rpc_method_handler(
                    servicer.ListOperations,
                    request_deserializer=driver_dot_v1_dot_operation__service__pb2.ListOperationsRequest.FromString,
                    response_serializer=driver_dot_v1_dot_operation__service__pb2.ListOperationsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'nodeplane.driver.v1.OperationService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('nodeplane.driver.v1.OperationService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class OperationService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetOperation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/nodeplane.driver.v1.OperationService/GetOperation',
            driver_dot_v1_dot_operation__service__pb2.GetOperationRequest.SerializeToString,
            driver_dot_v1_dot_types__pb2.Operation.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def WatchOperation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/nodeplane.driver.v1.OperationService/WatchOperation',
            driver_dot_v1_dot_operation__service__pb2.WatchOperationRequest.SerializeToString,
            driver_dot_v1_dot_types__pb2.OperationEvent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListOperations(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/nodeplane.driver.v1.OperationService/ListOperations',
            driver_dot_v1_dot_operation__service__pb2.ListOperationsRequest.SerializeToString,
            driver_dot_v1_dot_operation__service__pb2.ListOperationsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
