# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from driver.v1 import provisioning_service_pb2 as driver_dot_v1_dot_provisioning__service__pb2
from driver.v1 import types_pb2 as driver_dot_v1_dot_types__pb2

GRPC_GENERATED_VERSION = '1.74.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in driver/v1/provisioning_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ProvisioningServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.EnsureProfileOnNode = channel.unary_unary(
                '/nodeplane.driver.v1.ProvisioningService/EnsureProfileOnNode',
                request_serializer=driver_dot_v1_dot_provisioning__service__pb2.EnsureProfileOnNodeRequest.SerializeToString,
                response_deserializer=driver_dot_v1_dot_types__pb2.StartOperationResponse.FromString,
                _registered_method=True)
        self.DeleteProfileFromNode = channel.unary_unary(
                '/nodeplane.driver.v1.ProvisioningService/DeleteProfileFromNode',
                request_serializer=driver_dot_v1_dot_provisioning__service__pb2.DeleteProfileFromNodeRequest.SerializeToString,
                response_deserializer=driver_dot_v1_dot_types__pb2.StartOperationResponse.FromString,
                _registered_method=True)
        self.ReconcileNode = channel.unary_unary(
                '/nodeplane.driver.v1.ProvisioningService/ReconcileNode',
                request_serializer=driver_dot_v1_dot_provisioning__service__pb2.ReconcileNodeRequest.SerializeToString,
                response_deserializer=driver_dot_v1_dot_types__pb2.StartOperationResponse.FromString,
                _registered_method=True)
        self.ReconcileProfile = channel.unary_unary(
                '/nodeplane.driver.v1.ProvisioningService/ReconcileProfile',
                request_serializer=driver_dot_v1_dot_provisioning__service__pb2.ReconcileProfileRequest.SerializeToString,
                response_deserializer=driver_dot_v1_dot_types__pb2.StartOperationResponse.FromString,
                _registered_method=True)
        self.ListRemoteProfiles = channel.unary_unary(
                '/nodeplane.driver.v1.ProvisioningService/ListRemoteProfiles',
                request_serializer=driver_dot_v1_dot_provisioning__service__pb2.ListRemoteProfilesRequest.SerializeToString,
                response_deserializer=driver_dot_v1_dot_provisioning__service__pb2.ListRemoteProfilesResponse.FromString,
                _registered_method=True)


class ProvisioningServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def EnsureProfileOnNode(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteProfileFromNode(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReconcileNode(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReconcileProfile(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListRemoteProfiles(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ProvisioningServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'EnsureProfileOnNode': grpc.unary_unary_rpc_method_handler(
                    servicer.EnsureProfileOnNode,
                    request_deserializer=driver_dot_v1_dot_provisioning__service__pb2.EnsureProfileOnNodeRequest.FromString,
                    response_serializer=driver_dot_v1_dot_types__pb2.StartOperationResponse.SerializeToString,
            ),
            'DeleteProfileFromNode': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteProfileFromNode,
                    request_deserializer=driver_dot_v1_dot_provisioning__service__pb2.DeleteProfileFromNodeRequest.FromString,
                    response_serializer=driver_dot_v1_dot_types__pb2.StartOperationResponse.SerializeToString,
            ),
            'ReconcileNode': grpc.unary_unary_rpc_method_handler(
                    servicer.ReconcileNode,
                    request_deserializer=driver_dot_v1_dot_provisioning__service__pb2.ReconcileNodeRequest.FromString,
                    response_serializer=driver_dot_v1_dot_types__pb2.StartOperationResponse.SerializeToString,
            ),
            'ReconcileProfile': grpc.unary_unary_rpc_method_handler(
                    servicer.ReconcileProfile,
                    request_deserializer=driver_dot_v1_dot_provisioning__service__pb2.ReconcileProfileRequest.FromString,
                    response_serializer=driver_dot_v1_dot_types__pb2.StartOperationResponse.SerializeToString,
            ),
            'ListRemoteProfiles': grpc.unary_unary_rpc_method_handler(
                    servicer.ListRemoteProfiles,
                    request_deserializer=driver_dot_v1_dot_provisioning__service__pb2.ListRemoteProfilesRequest.FromString,
                    response_serializer=driver_dot_v1_dot_provisioning__service__pb2.ListRemoteProfilesResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'nodeplane.driver.v1.ProvisioningService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('nodeplane.driver.v1.ProvisioningService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ProvisioningService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def EnsureProfileOnNode(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/nodeplane.driver.v1.ProvisioningService/EnsureProfileOnNode',
            driver_dot_v1_dot_provisioning__service__pb2.EnsureProfileOnNodeRequest.SerializeToString,
            driver_dot_v1_dot_types__pb2.StartOperationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteProfileFromNode(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/nodeplane.driver.v1.ProvisioningService/DeleteProfileFromNode',
            driver_dot_v1_dot_provisioning__service__pb2.DeleteProfileFromNodeRequest.SerializeToString,
            driver_dot_v1_dot_types__pb2.StartOperationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReconcileNode(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/nodeplane.driver.v1.ProvisioningService/ReconcileNode',
            driver_dot_v1_dot_provisioning__service__pb2.ReconcileNodeRequest.SerializeToString,
            driver_dot_v1_dot_types__pb2.StartOperationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReconcileProfile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/nodeplane.driver.v1.ProvisioningService/ReconcileProfile',
            driver_dot_v1_dot_provisioning__service__pb2.ReconcileProfileRequest.SerializeToString,
            driver_dot_v1_dot_types__pb2.StartOperationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListRemoteProfiles(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/nodeplane.driver.v1.ProvisioningService/ListRemoteProfiles',
            driver_dot_v1_dot_provisioning__service__pb2.ListRemoteProfilesRequest.SerializeToString,
            driver_dot_v1_dot_provisioning__service__pb2.ListRemoteProfilesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
