# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: driver/v1/provisioning_service.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'driver/v1/provisioning_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from driver.v1 import types_pb2 as driver_dot_v1_dot_types__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n$driver/v1/provisioning_service.proto\x12\x13nodeplane.driver.v1\x1a\x15\x64river/v1/types.proto\"a\n\x1a\x45nsureProfileOnNodeRequest\x12\x10\n\x08node_key\x18\x01 \x01(\t\x12\x31\n\x07profile\x18\x02 \x01(\x0b\x32 .nodeplane.driver.v1.ProfileSpec\"^\n\x1c\x44\x65leteProfileFromNodeRequest\x12\x10\n\x08node_key\x18\x01 \x01(\t\x12\x14\n\x0cprofile_name\x18\x02 \x01(\t\x12\x16\n\x0eprotocol_kinds\x18\x03 \x03(\t\"(\n\x14ReconcileNodeRequest\x12\x10\n\x08node_key\x18\x01 \x01(\t\"/\n\x17ReconcileProfileRequest\x12\x14\n\x0cprofile_name\x18\x01 \x01(\t\"D\n\x19ListRemoteProfilesRequest\x12\x10\n\x08node_key\x18\x01 \x01(\t\x12\x15\n\rprotocol_kind\x18\x02 \x01(\t\"U\n\x1aListRemoteProfilesResponse\x12\x37\n\x05items\x18\x01 \x03(\x0b\x32(.nodeplane.driver.v1.RemoteProfileRecord2\xd2\x04\n\x13ProvisioningService\x12s\n\x13\x45nsureProfileOnNode\x12/.nodeplane.driver.v1.EnsureProfileOnNodeRequest\x1a+.nodeplane.driver.v1.StartOperationResponse\x12w\n\x15\x44\x65leteProfileFromNode\x12\x31.nodeplane.driver.v1.DeleteProfileFromNodeRequest\x1a+.nodeplane.driver.v1.StartOperationResponse\x12g\n\rReconcileNode\x12).nodeplane.driver.v1.ReconcileNodeRequest\x1a+.nodeplane.driver.v1.StartOperationResponse\x12m\n\x10ReconcileProfile\x12,.nodeplane.driver.v1.ReconcileProfileRequest\x1a+.nodeplane.driver.v1.StartOperationResponse\x12u\n\x12ListRemoteProfiles\x12..nodeplane.driver.v1.ListRemoteProfilesRequest\x1a/.nodeplane.driver.v1.ListRemoteProfilesResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'driver.v1.provisioning_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ENSUREPROFILEONNODEREQUEST']._serialized_start=84
  _globals['_ENSUREPROFILEONNODEREQUEST']._serialized_end=181
  _globals['_DELETEPROFILEFROMNODEREQUEST']._serialized_start=183
  _globals['_DELETEPROFILEFROMNODEREQUEST']._serialized_end=277
  _globals['_RECONCILENODEREQUEST']._serialized_start=279
  _globals['_RECONCILENODEREQUEST']._serialized_end=319
  _globals['_RECONCILEPROFILEREQUEST']._serialized_start=321
  _globals['_RECONCILEPROFILEREQUEST']._serialized_end=368
  _globals['_LISTREMOTEPROFILESREQUEST']._serialized_start=370
  _globals['_LISTREMOTEPROFILESREQUEST']._serialized_end=438
  _globals['_LISTREMOTEPROFILESRESPONSE']._serialized_start=440
  _globals['_LISTREMOTEPROFILESRESPONSE']._serialized_end=525
  _globals['_PROVISIONINGSERVICE']._serialized_start=528
  _globals['_PROVISIONINGSERVICE']._serialized_end=1122
# @@protoc_insertion_point(module_scope)
