# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from driver.v1 import runtime_service_pb2 as driver_dot_v1_dot_runtime__service__pb2
from driver.v1 import types_pb2 as driver_dot_v1_dot_types__pb2

GRPC_GENERATED_VERSION = '1.74.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in driver/v1/runtime_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class RuntimeServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.BootstrapNode = channel.unary_unary(
                '/nodeplane.driver.v1.RuntimeService/BootstrapNode',
                request_serializer=driver_dot_v1_dot_runtime__service__pb2.BootstrapNodeRequest.SerializeToString,
                response_deserializer=driver_dot_v1_dot_types__pb2.StartOperationResponse.FromString,
                _registered_method=True)
        self.ReinstallNode = channel.unary_unary(
                '/nodeplane.driver.v1.RuntimeService/ReinstallNode',
                request_serializer=driver_dot_v1_dot_runtime__service__pb2.ReinstallNodeRequest.SerializeToString,
                response_deserializer=driver_dot_v1_dot_types__pb2.StartOperationResponse.FromString,
                _registered_method=True)
        self.DeleteRuntime = channel.unary_unary(
                '/nodeplane.driver.v1.RuntimeService/DeleteRuntime',
                request_serializer=driver_dot_v1_dot_runtime__service__pb2.DeleteRuntimeRequest.SerializeToString,
                response_deserializer=driver_dot_v1_dot_types__pb2.StartOperationResponse.FromString,
                _registered_method=True)
        self.FullCleanupNode = channel.unary_unary(
                '/nodeplane.driver.v1.RuntimeService/FullCleanupNode',
                request_serializer=driver_dot_v1_dot_runtime__service__pb2.FullCleanupNodeRequest.SerializeToString,
                response_deserializer=driver_dot_v1_dot_types__pb2.StartOperationResponse.FromString,
                _registered_method=True)
        self.SyncRuntime = channel.unary_unary(
                '/nodeplane.driver.v1.RuntimeService/SyncRuntime',
                request_serializer=driver_dot_v1_dot_runtime__service__pb2.SyncRuntimeRequest.SerializeToString,
                response_deserializer=driver_dot_v1_dot_types__pb2.StartOperationResponse.FromString,
                _registered_method=True)
        self.SyncXray = channel.unary_unary(
                '/nodeplane.driver.v1.RuntimeService/SyncXray',
                request_serializer=driver_dot_v1_dot_runtime__service__pb2.SyncXrayRequest.SerializeToString,
                response_deserializer=driver_dot_v1_dot_types__pb2.StartOperationResponse.FromString,
                _registered_method=True)
        self.GetRuntimeStatus = channel.unary_unary(
                '/nodeplane.driver.v1.RuntimeService/GetRuntimeStatus',
                request_serializer=driver_dot_v1_dot_runtime__service__pb2.GetRuntimeStatusRequest.SerializeToString,
                response_deserializer=driver_dot_v1_dot_runtime__service__pb2.GetRuntimeStatusResponse.FromString,
                _registered_method=True)
        self.ListNodesNeedingRuntimeSync = channel.unary_unary(
                '/nodeplane.driver.v1.RuntimeService/ListNodesNeedingRuntimeSync',
                request_serializer=driver_dot_v1_dot_runtime__service__pb2.ListNodesNeedingRuntimeSyncRequest.SerializeToString,
                response_deserializer=driver_dot_v1_dot_runtime__service__pb2.ListNodesNeedingRuntimeSyncResponse.FromString,
                _registered_method=True)


class RuntimeServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def BootstrapNode(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReinstallNode(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteRuntime(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FullCleanupNode(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SyncRuntime(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SyncXray(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetRuntimeStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListNodesNeedingRuntimeSync(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RuntimeServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'BootstrapNode': grpc.unary_unary_rpc_method_handler(
                    servicer.BootstrapNode,
                    request_deserializer=driver_dot_v1_dot_runtime__service__pb2.BootstrapNodeRequest.FromString,
                    response_serializer=driver_dot_v1_dot_types__pb2.StartOperationResponse.SerializeToString,
            ),
            'ReinstallNode': grpc.unary_unary_rpc_method_handler(
                    servicer.ReinstallNode,
                    request_deserializer=driver_dot_v1_dot_runtime__service__pb2.ReinstallNodeRequest.FromString,
                    response_serializer=driver_dot_v1_dot_types__pb2.StartOperationResponse.SerializeToString,
            ),
            'DeleteRuntime': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteRuntime,
                    request_deserializer=driver_dot_v1_dot_runtime__service__pb2.DeleteRuntimeRequest.FromString,
                    response_serializer=driver_dot_v1_dot_types__pb2.StartOperationResponse.SerializeToString,
            ),
            'FullCleanupNode': grpc.unary_unary_rpc_method_handler(
                    servicer.FullCleanupNode,
                    request_deserializer=driver_dot_v1_dot_runtime__service__pb2.FullCleanupNodeRequest.FromString,
                    response_serializer=driver_dot_v1_dot_types__pb2.StartOperationResponse.SerializeToString,
            ),
            'SyncRuntime': grpc.unary_unary_rpc_method_handler(
                    servicer.SyncRuntime,
                    request_deserializer=driver_dot_v1_dot_runtime__service__pb2.SyncRuntimeRequest.FromString,
                    response_serializer=driver_dot_v1_dot_types__pb2.StartOperationResponse.SerializeToString,
            ),
            'SyncXray': grpc.unary_unary_rpc_method_handler(
                    servicer.SyncXray,
                    request_deserializer=driver_dot_v1_dot_runtime__service__pb2.SyncXrayRequest.FromString,
                    response_serializer=driver_dot_v1_dot_types__pb2.StartOperationResponse.SerializeToString,
            ),
            'GetRuntimeStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRuntimeStatus,
                    request_deserializer=driver_dot_v1_dot_runtime__service__pb2.GetRuntimeStatusRequest.FromString,
                    response_serializer=driver_dot_v1_dot_runtime__service__pb2.GetRuntimeStatusResponse.SerializeToString,
            ),
            'ListNodesNeedingRuntimeSync': grpc.unary_unary_rpc_method_handler(
                    servicer.ListNodesNeedingRuntimeSync,
                    request_deserializer=driver_dot_v1_dot_runtime__service__pb2.ListNodesNeedingRuntimeSyncRequest.FromString,
                    response_serializer=driver_dot_v1_dot_runtime__service__pb2.ListNodesNeedingRuntimeSyncResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'nodeplane.driver.v1.RuntimeService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('nodeplane.driver.v1.RuntimeService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class RuntimeService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def BootstrapNode(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/nodeplane.driver.v1.RuntimeService/BootstrapNode',
            driver_dot_v1_dot_runtime__service__pb2.BootstrapNodeRequest.SerializeToString,
            driver_dot_v1_dot_types__pb2.StartOperationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReinstallNode(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/nodeplane.driver.v1.RuntimeService/ReinstallNode',
            driver_dot_v1_dot_runtime__service__pb2.ReinstallNodeRequest.SerializeToString,
            driver_dot_v1_dot_types__pb2.StartOperationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteRuntime(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/nodeplane.driver.v1.RuntimeService/DeleteRuntime',
            driver_dot_v1_dot_runtime__service__pb2.DeleteRuntimeRequest.SerializeToString,
            driver_dot_v1_dot_types__pb2.StartOperationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def FullCleanupNode(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/nodeplane.driver.v1.RuntimeService/FullCleanupNode',
            driver_dot_v1_dot_runtime__service__pb2.FullCleanupNodeRequest.SerializeToString,
            driver_dot_v1_dot_types__pb2.StartOperationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SyncRuntime(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/nodeplane.driver.v1.RuntimeService/SyncRuntime',
            driver_dot_v1_dot_runtime__service__pb2.SyncRuntimeRequest.SerializeToString,
            driver_dot_v1_dot_types__pb2.StartOperationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SyncXray(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/nodeplane.driver.v1.RuntimeService/SyncXray',
            driver_dot_v1_dot_runtime__service__pb2.SyncXrayRequest.SerializeToString,
            driver_dot_v1_dot_types__pb2.StartOperationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetRuntimeStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/nodeplane.driver.v1.RuntimeService/GetRuntimeStatus',
            driver_dot_v1_dot_runtime__service__pb2.GetRuntimeStatusRequest.SerializeToString,
            driver_dot_v1_dot_runtime__service__pb2.GetRuntimeStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListNodesNeedingRuntimeSync(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/nodeplane.driver.v1.RuntimeService/ListNodesNeedingRuntimeSync',
            driver_dot_v1_dot_runtime__service__pb2.ListNodesNeedingRuntimeSyncRequest.SerializeToString,
            driver_dot_v1_dot_runtime__service__pb2.ListNodesNeedingRuntimeSyncResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
