# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: driver/v1/telemetry_service.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'driver/v1/telemetry_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from driver.v1 import types_pb2 as driver_dot_v1_dot_types__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n!driver/v1/telemetry_service.proto\x12\x13nodeplane.driver.v1\x1a\x15\x64river/v1/types.proto\"2\n\x1d\x43ollectTrafficSnapshotRequest\x12\x11\n\tnode_keys\x18\x01 \x03(\t\"U\n\x16GetProfileUsageRequest\x12\x14\n\x0cprofile_name\x18\x01 \x01(\t\x12\x15\n\rprotocol_kind\x18\x02 \x01(\t\x12\x0e\n\x06period\x18\x03 \x01(\t\"K\n\x17GetProfileUsageResponse\x12\x30\n\x05usage\x18\x01 \x01(\x0b\x32!.nodeplane.driver.v1.ProfileUsage2\xfb\x01\n\x10TelemetryService\x12y\n\x16\x43ollectTrafficSnapshot\x12\x32.nodeplane.driver.v1.CollectTrafficSnapshotRequest\x1a+.nodeplane.driver.v1.StartOperationResponse\x12l\n\x0fGetProfileUsage\x12+.nodeplane.driver.v1.GetProfileUsageRequest\x1a,.nodeplane.driver.v1.GetProfileUsageResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'driver.v1.telemetry_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_COLLECTTRAFFICSNAPSHOTREQUEST']._serialized_start=81
  _globals['_COLLECTTRAFFICSNAPSHOTREQUEST']._serialized_end=131
  _globals['_GETPROFILEUSAGEREQUEST']._serialized_start=133
  _globals['_GETPROFILEUSAGEREQUEST']._serialized_end=218
  _globals['_GETPROFILEUSAGERESPONSE']._serialized_start=220
  _globals['_GETPROFILEUSAGERESPONSE']._serialized_end=295
  _globals['_TELEMETRYSERVICE']._serialized_start=298
  _globals['_TELEMETRYSERVICE']._serialized_end=549
# @@protoc_insertion_point(module_scope)
