# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from driver.v1 import telemetry_service_pb2 as driver_dot_v1_dot_telemetry__service__pb2
from driver.v1 import types_pb2 as driver_dot_v1_dot_types__pb2

GRPC_GENERATED_VERSION = '1.74.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in driver/v1/telemetry_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class TelemetryServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CollectTrafficSnapshot = channel.unary_unary(
                '/nodeplane.driver.v1.TelemetryService/CollectTrafficSnapshot',
                request_serializer=driver_dot_v1_dot_telemetry__service__pb2.CollectTrafficSnapshotRequest.SerializeToString,
                response_deserializer=driver_dot_v1_dot_types__pb2.StartOperationResponse.FromString,
                _registered_method=True)
        self.GetProfileUsage = channel.unary_unary(
                '/nodeplane.driver.v1.TelemetryService/GetProfileUsage',
                request_serializer=driver_dot_v1_dot_telemetry__service__pb2.GetProfileUsageRequest.SerializeToString,
                response_deserializer=driver_dot_v1_dot_telemetry__service__pb2.GetProfileUsageResponse.FromString,
                _registered_method=True)


class TelemetryServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CollectTrafficSnapshot(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetProfileUsage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TelemetryServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CollectTrafficSnapshot': grpc.unary_unary_rpc_method_handler(
                    servicer.CollectTrafficSnapshot,
                    request_deserializer=driver_dot_v1_dot_telemetry__service__pb2.CollectTrafficSnapshotRequest.FromString,
                    response_serializer=driver_dot_v1_dot_types__pb2.StartOperationResponse.SerializeToString,
            ),
            'GetProfileUsage': grpc.unary_unary_rpc_method_handler(
                    servicer.GetProfileUsage,
                    request_deserializer=driver_dot_v1_dot_telemetry__service__pb2.GetProfileUsageRequest.FromString,
                    response_serializer=driver_dot_v1_dot_telemetry__service__pb2.GetProfileUsageResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'nodeplane.driver.v1.TelemetryService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('nodeplane.driver.v1.TelemetryService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class TelemetryService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CollectTrafficSnapshot(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/nodeplane.driver.v1.TelemetryService/CollectTrafficSnapshot',
            driver_dot_v1_dot_telemetry__service__pb2.CollectTrafficSnapshotRequest.SerializeToString,
            driver_dot_v1_dot_types__pb2.StartOperationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetProfileUsage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/nodeplane.driver.v1.TelemetryService/GetProfileUsage',
            driver_dot_v1_dot_telemetry__service__pb2.GetProfileUsageRequest.SerializeToString,
            driver_dot_v1_dot_telemetry__service__pb2.GetProfileUsageResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
